
# html languages
language:
- zh-Hans
- en

# main menu navigation
menu:
  Home: /index.html
#  Archives: /archives
#  About: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/aloha.css
#- /css/semantic.min.css
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css
- /css/github-v2.min.css

# scripts loaded in the end of the body
scripts:
- https://cdn.jsdelivr.net/jquery/3.1.0/jquery.min.js
#- /js/jquery-3.1.0.min.js
#- /js/semantic.min.js
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js
- /js/prettify.js
- /js/aloha.js