# html languages
language:
- zh-Hans
- en

# main menu navigation
menu:
  Home:
    name: homePage
    value: /index.html
#  About:
#    name: aboutPage
#    value: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/aloha.css
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css
- /css/prettify-github-v2.min.css
- /css/scrolltop.css

# scripts loaded in the end of the body
scripts:
- https://cdn.jsdelivr.net/jquery/3.1.0/jquery.min.js
- /js/jquery.scrollUp.min.js
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js
- /js/prettify.js
- /js/aloha.js