# html languages
language:
- zh-Hans
- en

# main menu navigation
# icon name see http://semantic-ui.com/elements/icon.html
menu:
  Home:
    name: homePage
    value: /index.html
    icon: home
  Rss:
    name: rss
    value: /atom.xml
    icon: rss
  About:
    name: aboutPage
    value: /about
    icon:

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/aloha.css
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.css
- /css/prettify-github-v2.min.css
- /css/scrolltop.css

# scripts loaded in the end of the body
scripts:
#- https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js
- https://cdn.jsdelivr.net/jquery/3.1.0/jquery.min.js
- /js/jquery.scrollUp.min.js
- https://cdn.jsdelivr.net/semantic-ui/2.2.4/semantic.min.js
- /js/prettify.js
- https://cdn.jsdelivr.net/g/algoliasearch@3(algoliasearchLite.min.js),algoliasearch.helper@2
- /js/semantic-ui-algolia.js
- /js/aloha-events.js
- /js/aloha.js
